### PR TITLE
Add SecureString password support

### PR DESCRIPTION
**Pull request by michaelwanke**
Would you consider a modification that would allow a SecureString to be passed to the Impersonation call? If so, is there anything I can do to improve the changes I have included? Thank you for your consideration.

### CODE REVIEW

**Comment by apmorton** [comment]
+1 on this - SecureString is a must.

The only thing I would change is leaving `_handle` and `_context` readonly, and pass them through to `CompleteImpersonation` as reference parameters

Realistically this change has no effect on the behavior of the code, but it enforces the original intent that those fields be readonly for the lifetime of the object

**Comment by mj1856** [comment]
Looks good to me.  Thanks, and sorry I didn't get to this sooner!

@apmorton - That wouldn't help, as the value would still have to be modified.  I'm fine removing `readonly`.

**Comment by mj1856** [comment]
merged 78d9a34125f01e1ec19e638c4b66011322bff6ed.  I'll bump the version (to 1.1.0) separately before release (soon).

**Comment by apmorton** [comment]
@mj1856 this is an example of what I am proposing

```c#
    class Class1
    {
        private readonly string _test;

        public Class1()
        {
            test(ref _test);
        }

        private void test(ref string t)
        {
            t = "hello world";
        }
    }
```

that code is perfectly valid, compiles, works, and preserves the readonly-ness of `_test`

**Comment by mj1856** [comment]
That feels wrong to me... Not sure how it could truly be considered "read-only" then.  Let me ponder on this for a bit.

I asked here: http://stackoverflow.com/questions/34552287/why-can-readonly-fields-be-modified-through-ref-parameters

**Comment by apmorton** [comment]
It is of course important to note that this only works if you pass it by ref FROM the constructor.

Perhaps `out` is better suited for this than `ref`, but the concept is the same.

**Comment by michaelwanke** [comment]
Thank you for the discussion and bringing these changes in!

**Comment by mj1856** [comment]
No problem.  I did some minor refactoring per @apmorton 's feedback.

**Pull request closed without merging**
